# Everything in ruby is an object, it is object oriented
class  Animal
  def initialize
    puts "Creating a New Animal"
  end

  def set_name(new_name)
    @name = new_name
  end

  def get_name
    @name
  end

  def name
    @name
  end

  def name=(new_name)
    if new_name.is_a?(Numeric)
        puts "Name Can't be a number"
    else
        @name = new_name
    end
  end

end


cat = Animal.new

cat.set_name("Peekaboo")
puts cat.get_name
puts cat.name

cat.name = "Sophie"

# creating a new class with autogenerated getters and setters

class DogExample
    attr_reader :weight
    attr_writer :weight
end

class Dog
    attr_accessor :name, :height, :weight

    def bark 
        return "Generic Bark"
    end
end


rover = Dog.new
rover.name = "Rover"
puts rover.name, "is the Dog name"


# Inheritance
class GermanShepard < Dog
    def bark
        return "Loud bark"
    end
end

max = GermanShepard.new
max.name = "max"

puts "My dog's name is #{max.name}"